version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - quovidi
    restart: always
    environment:
      DOMAINS: 't3ta.net -> http://quovidi:3838'
  quovidi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/srv/shiny-server
    working_dir: /srv/shiny-server
    command:
      sh -c 'Rscript ./app/www/setup_database_biogo.R'

