version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - quovidi
    restart: always
    environment:
      DOMAINS: 'quovidi.t3ta.net -> http://quovidi:3838'
      STAGE: production
      ERROR_LOG: default
      ACCESS_LOG: default
      WEBSOCKET: 'true'
    volumes:
      - ./ssl_certs:/var/lib/https-portal
      - ./logs:/var/log/nginx
  quovidi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3838:3838'
    volumes:
      - ./app:/srv/shiny-server
